env                                = "prod"
region                             = "us-east-1"
aws_account_number                 = "332281781429"
created_by                         = "BizCloudExperts"
application                        = "omni-pb-wt-milestone-updates"
omni_pb_add_milestone_emails       = ["omnidev@bizcloudexperts.com", "support@bizcloudexperts.com"]
omni_ivia_addMilestone_console_url = "https://worldtrak.omnilogistics.com/WTKServices/shipments.asmx?op=UpdateStatusByConsolNo"
omni_loadtracking_url              = "https://tms-lvlp.loadtracking.com/ws/api/images"
omni_wt_upload_doc_url             = "https://api.omnilogistics.com/v1/uploadpoddocument"
omni_wt_upload_doc_api_key         = "JPRy7nJdcN40eaIfQN685Xprw8kK1zF8ZYCS8Zi6"